-- Shyne Lua API Standard 2.0 module index.
--
-- The Java host concatenates the files in `avatar/` and compiles them as one
-- Lua chunk. Concatenation preserves private `local` helpers while keeping each
-- source file small enough to review. Avatar authors do not load these files or
-- call require(); the complete native API is ready before script.lua executes.
--
-- Load order:
--   avatar/00_core.lua
--   avatar/10_model_animation.lua
--   avatar/20_avatar_world.lua
--   avatar/30_render_tasks.lua
--   avatar/31_render_shapes.lua
--   avatar/40_optional_systems.lua
--   avatar/50_easy_api.lua
