name = "shyne-avatar-cloud"
main = "src/index.ts"
compatibility_date = "2025-09-01"

[[r2_buckets]]
binding = "AVATAR_BUCKET"
bucket_name = "shyne-avatars"

[[d1_databases]]
binding = "DB"
database_name = "shyne-cloud-db"
database_id = "d866798b-bbfd-47be-8c1c-dd6bebdedd94"

[vars]
MOJANG_SESSION_URL = "https://sessionserver.mojang.com/session/minecraft/hasJoined"
